apiVersion: v1
kind: Namespace
metadata:
  name: staging-motopay-ns
  labels:
    name: staging-motopay-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plenti-backend-service-deployment
  namespace: staging-motopay-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plenti-backend-service
  template:
    metadata:
      labels:
        app: plenti-backend-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: plenti-backend-service
        image: swr.af-south-1.myhuaweicloud.com/moto/plenti-backend-service:d24c0fc26d690fb6aa9deb1386449659ed232d4d
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
        env:
          - name: DB_URL
            value: "jdbc:mysql://c039e01d33724bf4b444c7a5277a38c2in01.internal. af-south-1.mysql. rds.myhuaweicloud.com/plenti_db? createDatabaseIfNotExist=true&autoReconnect=TRUE"
          - name: DB_USERNAME
            value: "root"
          - name: DB_PASSWORD
            value: "Motopay@010224"
          - name: JWT_SECRET
            value: "mJtBSGr/RbOYN6j4K2t2HCSEPVPU8iUdOhb4kWLkinmRyLe1AvvHx0gZExapUecvKrqYIYUeZilgaKFosD3PKA=="
          - name: CORS_ORIGINS
            value: "http://localhost:3000,http://localhost:4200,https://plenti-frontend.onrender.com,https://plenti-backend.staging-api.motopayng. com"
          - name: MONNIFY_API_KEY
            value: ""
          - name: MONNIFY_SECRET_KEY
            value: ""
          - name: MONNIFY_CONTRACT_CODE
            value: ""
          - name: MONNIFY_BASE_URL
            value: "https://sandbox.monnify.com"
          - name: MAIL_HOST
            value: "smtp. gmail.com"
          - name: MAIL_PORT
            value: "587"
          - name: MAIL_USERNAME
            value: ""
          - name: MAIL_PASSWORD
            value: ""
          - name: SMS_API_KEY
            value: ""
        # envFrom:
        #   - secretRef:
        #       name: plenti-backend-secret
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 500Mi
        readinessProbe:  
         tcpSocket:
           port: 8080
         initialDelaySeconds: 15
         periodSeconds: 10
        livenessProbe:  
         tcpSocket:
           port: 8080
         initialDelaySeconds: 90
         periodSeconds: 90
  
      imagePullSecrets:
        - name: default-secret
---
apiVersion: v1
kind: Service
metadata:
  name: plenti-backend-service
  namespace: staging-motopay-ns
spec:
  type: NodePort  # Change service type to NodePort
  selector:
    app: plenti-backend-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: 30221  # Define a specific nodePort value (replace with desired port number).

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kubeissuer-plenti-backend
  namespace: staging-motopay-ns
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: seun.motopay@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: kubeissuer-plenti-backend
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubecert-plenti-backend
  namespace: staging-motopay-ns
spec:
  secretName: plenti-backend
  issuerRef:
    name: kubeissuer-plenti-backend
    kind: ClusterIssuer
  commonName: plenti-backend.staging-api.motopayng.com
  dnsNames:
  - plenti-backend.staging-api.motopayng.com

---
apiVersion: networking.k8s. io/v1
kind: Ingress
metadata:
  name: plenti-backend-ingress
  namespace: staging-motopay-ns
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
#     #nginx.ingress. kubernetes.io/ssl-redirect: "true"
spec:
  tls:
   - hosts:
     - plenti-backend. staging-api.motopayng.com
     secretName: plenti-backend
  rules:
  - host: plenti-backend.staging-api.motopayng.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: plenti-backend-service
            port:


              number: 8080